<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DecompilerCLI</AssemblyName>
    <RootNamespace>DecompilerCLI</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Decomp.csproj" />
  </ItemGroup>
</Project>
