<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Decomp</AssemblyName>
    <RootNamespace>Decomp.Core</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Core/**/*.cs" />
    <None Include="DecompilerGUI/**/*" />
  </ItemGroup>
</Project>
